Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/08/2024
Var
// Seção de Declarações das variáveis 
 contador:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para contador de 0 ate 50 passo 1 faça
escreval ("teste")
fimpara

Fimalgoritmo