Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/08/2024
Var
// Seção de Declarações das variáveis 
notas:vetor [1..10] de inteiro
 contador:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

para contador de 1 ate 10 passo 1 faça
escreval("INFORME A NOTA DO ALUNO nº" , contador)
LEIA (notas[contador])
fimpara

para contador de 1 ate 10 passo 1 faça
escreval("A NOTA DO ALUNO nº" , contador)
escreval ("é:" , notas[contador])
fimpara

Fimalgoritmo