Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/08/2024
Var
// Seção de Declarações das variáveis 
notas:vetor [1..10] de inteiro
 contador:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
notas[1] :=8
notas[2] :=8
notas[3] :=5
notas[4] :=3
notas[5] :=10
notas[6] :=6
notas[7] :=9
notas[8] :=1
notas[9] :=8
notas[10] :=2

para contador de 1 ate 10 passo 1 faça
escreval(notas[contador])
fimpara

fimescolha
fimpara
Fimalgoritmo