Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/08/2024
Var
// Seção de Declarações das variáveis 
nota:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
ESCREVAL ("DIGITE UMA NOTA DE 0 A 10 PARA NOSSO ATENDIMENTO")
LEIA(nota)
SE nota >10 entao
ESCREVAL ("NOTA INVÁLIDA")
SENAO
ESCOLHA nota
        caso 10 entao
ESCREVAL ("Excelente")
         caso 9 entao
ESCREVAL ("Excelente")
         caso 8 entao
ESCREVAL ("Bom")
         caso 7 entao
ESCREVAL ("Bom")
         caso 6 entao
ESCREVAL ("Regular")
         caso 5 entao
ESCREVAL ("Regular")
         caso 4 entao
ESCREVAL ("Insuficiente")
         Caso 3 entao
ESCREVAL ("Insuficiente")
         Caso 2 entao
ESCREVAL ("Insuficiente")
         Caso 1 entao
ESCREVAL ("Insuficient")
fimescolha
fimse
Fimalgoritmo