Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/08/2024
Var
// Seção de Declarações das variáveis 
idade:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
ESCREVAL ("DIGITE A SUA IDADE")
LEIA(idade)
SE idade>18 entao
ESCREVAL ("você já é maior de idade e pode usufruir desse conteúdo")
SE idade<18 entao
ESCREVAL ("Ops, Você é menor de idade, portanto NÃO TEM PERMISSÃO para consumir esse conteúdo")
SE idade=18 entao
ESCREVAL ("Parabéns, seja bem vindo a maior idade, mas não se esqueça de consumir com responsabilidade")

FIMSE

Fimalgoritmo