Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/10/2024
Var
// Seção de Declarações das variáveis 
servico : vetor [1..10] de real
contador: inteiro

Inicio
contador <- 1
para contador de 1 até 10 faça
  escreval ("digite o valor do seu serviço")
  leia (servico[contador])
fimpara


Fimalgoritmo